#!/usr/bin/awk -f
function gcd(a, b) {
    orig_a = a; orig_b = b; 
    old_x = 1; x = 0;
    old_y = 0; y = 1;
    print "r q x y a*x+b*y=r";
    print a,"-",old_x,old_y,orig_a"*"old_x"+"orig_b"*"old_y"="a;
    while(b != 0) {
        q = int(a/b);
        tmp = x; x = old_x - q * x; old_x = tmp;
        tmp = y; y = old_y - q * y; old_y = tmp;
        tmp = b; b = a % b; a = tmp;
        print a,q,old_x,old_y,orig_a"*"old_x"+"orig_b"*"old_y"="a;
    }
}
$1 && $2 { gcd($1, $2) }
