#!/bin/sh

# Script for converting tabular data into markdown syntax. Examples:

usage() {
  printf 'Usage:\n%s [options] < file\n' "$0" >&2
  printf 'Options:\n'
  printf ' -F awk-field-sep-string:\n'
  printf '   Set input field delim (awk syntax). Default: any run of whitespaces\n'
  printf 'Example:\n'
  printf ' $ printf "foo bar foobar\\naa bb c\\n" | marktable\n'
  printf '  | foo | bar | foobar |\n'
  printf '  |-----|-----|--------|\n'
  printf '  | aa  | bb  | c      |\n'
  exit 1
}

# swallow field sep (first arg), and surround each field with space and pipe
pipize() {
    awk -F "$1" -v OFS=" | " '{ $1=$1; printf "| %s |\n", $0 }'
}
columnize() {
    column -t -s "|" -o "|"
}
# insert delim row (like |---|-|--|) beetween header and body
head_delim() {
    awk '{print} NR==1{gsub(/[^|]/, "-", $0); print}'
}

if [ "$1" = '-F' ] && [ "$#" -eq 2 ]; then
    sep="$2"
else
    [ "$#" -eq 0 ] || usage
    sep='[ \t\n]+'
fi

pipize "$sep" <&0 | columnize | head_delim
