#!/bin/sh

# script for converting tabular data into markdown syntax
# NOTE: it works only if your fields do not nest whitespaces
# TODO: Allow for specifining cust input field separator

usage() {
  printf 'Usage:\n%s < file\n... | %s\n' "$0" "$0" >&2
  exit 1
}
# swallow current field sep, and surround each field with space and pipe
pipize() {
    awk -v OFS=" | " '{ $1=$1; printf "| %s |\n", $0 }'
}
columnize() {
    column -t -s "|" -o "|"
}
# insert delim row (like |---|-|--|) beetween header and body
head_delim() {
    awk '{print} NR==1{gsub(/[^|]/, "-", $0); print}'
}

if [ "$#" -ne 0 ]; then usage; fi

pipize <&0 | columnize | head_delim
