#!/bin/sh

# Do screenshot and save it on disk with cur time as filename
# License: Public Domain. Dependencies: maim, xclip

filename=~/Pictures/screeny/$(date +%F-%T).png

case $1 in
    select)
        maim -s --format png $filename && xclip -sel clipboard -t image/png -i $filename
        ;;
    window)
        maim -i $(xdotool getactivewindow) $filename && xclip -sel clipboard -t image/png -i $filename
        ;;
    fullscreen)
        maim --format png $filename && xclip -sel clipboard -t image/png -i $filename
        ;;
    *)
        printf "Usage: screenshoot {select|window|fullscreen}\n"
        exit
        ;;
esac
